<div class="container">
        <form class="user">
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="Nombre">
                    </div>
                    <div class="col-sm-6">
                        <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Edad">
                    </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user" id="exampleInputEmail" placeholder="Puesto">
                    </div>
                </div>
                <a href="login.html" class="btn btn-primary btn-user">
                  Actualizar
                </a>
                <a href="login.html" class="btn btn-danger btn-user">
                  Cancelar
                </a>
                <hr>
        </form>
</div>