<?=$this->titulo?>

<div class="container">
<div class="table-responsive">
<table class="table table-bordered text-center personal" id="dataTable">
    <thead>
        <tr>
            <td>ID</td>
            <td>Nombre</td>
            <td>Edad</td>
            <td>Puesto</td>
            <td>Acciones</td>
            
        </tr>
    </thead>

    <tbody>
        <?=$this->contenido?>
    </tbody>
</table>
</div>
</div>


  <!-- Logout Modal-->
  <div class="modal fade" id="agregarModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Agregar Usuario</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            <form class="user" method="POST" id="agregarP">
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="name" placeholder="Nombre">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="age" placeholder="Edad">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="puesto" placeholder="Puesto">
                </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-success">Add</button>
        </div>

        </form>
      </div>
    </div>
  </div>