
<div class="container">
  <div class="row">
  <?php if(isset($this->mensaje)) echo $this->mensaje; ?>
    <form action="" method="post" class="">
        <input type="hidden" value="1" name="ingresar">

        <div class="form-group">
            <label for="usuario"usuario></label>
            <input type="text" name="usuario" id="usuario" class="form-control"   placeholder="usuario">
        </div>

        <div class="form-group">
            <label for="usuario"usuario></label>
            <input type="password" name="clave" id="clave" class="form-control" placeholder="contraseña">
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-primary btn-block" value="Ingresar">
        </div>
    </form>
   </div>
</div>